### ISSUE TITLE
为什么类型定义都使用interface而不是declare class？

### ISSUE THREAD

**Issue by cumtfc** [xieziyu/ngx-amap#1]
### Typescript中`interface`和`declare class`的使用场景能麻烦科普一下吗？

**Comment by xieziyu** [comment]
@cumtfc 
抱歉回复的比较晚，最近工作实在太忙。

你的理解是对的，描述已存在的类，使用`declare class`更符合语义。因此在这个项目中，诸如`AMap.Marker`这样的类，用`declare class`描述会更恰当。

另一方面，比如在构造`Marker`时，所需要使用的`MarkerOptions`，这是一个典型的接口描述类型，传入构造函数的对象只需满足该接口定义的类型即可，而没有与之对应的类。所以用`interface`去描述这类接口最为合适。

在`ngx-amap`中，设计了多种指令去构造各类高德的图形对象，例如`amap-marker`，它需要与之相对应的`@Input`数据绑定，用于接收构造`Marker`所需要的`MarkerOptions`属性。其中你会发现，有的属性，例如`offset`，它原本是`AMap.Pixel`类型。如果拘泥于`MarkerOptions`接口中要求的类型，那就必须要求用户传入构造好的`Pixel`对象。但从使用的角度来看，直接传入`x`, `y`更加安全，直观，这样可以避免用户直接访问`AMap`这个全局对象。

`ngx-amap`中的很多设计，都是为了最终避免用户显式地访问`AMap`对象，因为它是被懒加载的，只有在异步加载完高德的JS库之后，才能够安全访问。正由于此，我也不希望用户通过`AMap.Marker`或是别的类去显式构造这些对象。因此将它们统一描述成`interface`也没给自己带来太多的困扰。
