### ISSUE TITLE
如何动态添加markder点？

### ISSUE THREAD

**Issue by qq35577925** [xieziyu/ngx-amap#17]
您好，看见您demo里，添加mark点
<amap-marker [position]="[116.397428, 39.90923]" [hidden]="hidden" [icon]="icon" [label]="label"></amap-marker>

这样，position 参数是写死的，不会有问题，

我需要动态去改变它的值，默认是空的，因此就设置了一个变量，[position]="pp"，但是，再去修改pp的值，它就不显示，请问如何解决，谢谢

**Comment by xieziyu** [comment]
有几种方式：

1. pp 给默认值 null 或者 undefined都行，等拿到position参数，再赋值给pp

2. 或者在ngx-amap上绑定`(ready)="onMapReady($event)"，然后在component里：
```typescript
declare const AMap: any;

@Component
// ...
onMapReady(map: any) {
  // 从这个事件开始，就可以像原生一样使用AMap
  // 例如直接new AMap.marker，参数map则是生成的地图对象。
}
```

**Comment by qq35577925** [comment]
默认值我给 []，不显示，按您说的 用null，正常了，谢谢您。
