### ISSUE TITLE
地理编码报错~

### ISSUE THREAD

**Issue by qq35577925** [xieziyu/ngx-amap#19]
您好，在ng-zorro的子组件里，调用 将经纬度转地理位置方法，报错：
core.js:1448 ERROR Error: Uncaught (in promise): TypeError: AMap.Geocoder is not a constructor

不在子组件是可以的。看到请指点下，谢谢。

**Comment by xieziyu** [comment]
@qq35577925 报错的页面有加载地图吗？

**Comment by qq35577925** [comment]
加载地图的界面正常，未加载的报错啦。暂时不需要计算了。谢谢可
