### ISSUE TITLE
在ionic 4 for angular 环境中. 无法触moveStart moveEnd事件

### ISSUE THREAD

**Issue by JunLiangW** [xieziyu/ngx-amap#21]
在桌面谷歌浏览器和微信web开发者工具中都无法触发.
现在只能用鼠标点击选取定位点.而不是拖动选取地图中心点

**Comment by JunLiangW** [comment]
amap.moveend.subscribe  是可以订阅事件的.

**Comment by xieziyu** [comment]
@JunLiangW Sorry, 演示页面的文档写错了，我会更新一下。
对应的事件应该是(movestart) 和 (moveend)，历史遗留原因这几个没大写
