### ISSUE TITLE
amapAutocomplete 切换city时不起作用

### ISSUE THREAD

**Issue by kavinwang** [xieziyu/ngx-amap#23]
如下面的代码：
<input amapAutocomplete type="text" [city]="currCity.cityName" citylimit="true" class="form-control" placeholder="请输入地址关键字...">
当currCity改变时，此时的关键词搜索的结果还是限定在原来的cityName上，并没有跟随新城市的改变而改变！

修改起来比较简单，也没啥复杂的算法，就不提pr了！

**Comment by xieziyu** [comment]
已在 v2.1.1 和 v1.3.3 中修复。
