### ISSUE TITLE
内存泄漏 memory leak

### ISSUE THREAD

**Issue by vinstics** [xieziyu/ngx-amap#24]
在demo中反复来回点击ngx-amap菜单下面的简单示例和调用方法页面，用Chrome开发工具可检测到显著的内存占用增长，百度地图的浏览器组件也有类似的不能完全释放的问题，有解决办法吗？

**Comment by vinstics** [comment]
solution: 直接嵌入高德地图，ngDestroy函数里调用地图的destroy可以完全销毁地图

**Comment by xieziyu** [comment]
@vinstics 这里可能有误解。
1. ngx-amap的组件本身在ngDestroy的时候，会调用高德的destroy函数，销毁地图。所以这不会造成内存泄漏，也不需要显式地调用。
2. 在简单示例和调用方法页面间来回切换，前几次会看到显著的内存占用增长是因为地图组件是被懒加载的，加载进来以后可以被反复使用，你会发现，每个页面首次加载的时候会明显增长，但之后会呈现稳定的内存使用情况。

**Comment by vinstics** [comment]
重新做了一遍更为细致的测试：
名词：H代表首页，A代指简单示例页面，B代指调用方法页面，E代表事件页面
环境：win10，Chrome 67 无痕模式，只打开demo网站
内存及类c的Objects Count变化：

|  页面  | c(Objects Count) | 内存(MB) |
|:------:|:---------------:|:--------:|
|      H |        1        |   12.2   |
| AB(50) |       337       |   21.5   |
| AB(50) |       387       |   23.4   |
| AB(50) |       437       |   24.7   |
| AB(50) |       487       |   25.4   |
|      H |       393       |   24.7   |
|  HE(5) |       826       |   56.4   |
|      H |       799       |   55.9   |

从上测试可以发现：
1、AB两个页面间切换也是有内存问题的，c类实例数量增长和点击次数完全一致，可能是点击事件泄露了。
2、E页面和H页面切换问题非常严重，仅仅切换5次即带来了严重的内存问题。

注：以上测试仅进行了一次，未重复验证规律，仅供参考

**Comment by xieziyu** [comment]
@vinstics 
非常感谢提供的详细测试数据，这很有助于我去检查组件和demo之间的逻辑。
我会在深入检查之后跟进这个问题。

由于发布的这些库都是我个人利用工作之余的时间去更新维护的，所以难免测试上会有疏漏，为此抱歉。

**Comment by vinstics** [comment]
@xieziyu 作为开源组件已经做得很好了，非常感谢，简单使用非常便利。我需要一个地图组件来使用户通过弹窗选取地点，所以涉及到反复init-destroy，找了一圈发现很多组件都忽略了不明显的内存问题，但这在我的应用场景里却是致命的。工作太忙，不然我也能花点时间研究一下这个内存问题的代码。目前我的方案如下，反复测试没有问题：


    this.map = new AMap.Map('lngLatSelector', option);
    this.clickBindRef = this.onClick.bind(this);
    this.map.on('click', this.clickBindRef);


    ngOnDestroy() {
        if (this.map) {
            this.map.off('click', this.clickBindRef);
            this.map.destroy();
        }
    }

**Comment by xieziyu** [comment]
@vinstics 
更新一下状态：
1. Event演示页面之所以有大量内存泄露是因为用了console.log，打印的那些地图事件对象不会被GC。这个我是为了演示event的内容，特意使用了console.log，所以这个问题可以忽略。（你可以本地运行我的demo示例，注释掉那个console.log再进行观察）

2. 我感兴趣的是每次切换页面时泄露的那1个c对象，因为你的方案中包括事件侦听器移除和destroy地图的方法，我的组件在销毁时都要调用的。所以暂时还没有确定泄露的那1个是什么。
