### ISSUE TITLE
do u add Coordinate Convert in ngx-amap?can't find AMap.convertFrom entry

### ISSUE THREAD

**Issue by ryansix** [xieziyu/ngx-amap#31]
do u add Coordinate Convert in ngx-amap?can't find AMap.convertFrom entry

**Comment by xieziyu** [comment]
@ryansix 
After `ngx-amap` (ready) event is emitted, you can use `AMap.convertFrom`.

**Comment by ryansix** [comment]
thx u! look forward to your renew
