### ISSUE TITLE
能否添加路径规划功能，非常感谢

### ISSUE THREAD

**Issue by zzcfree** [xieziyu/ngx-amap#32]

**Comment by xieziyu** [comment]
@zzcfree 
这个功能已开始开发。

**Comment by xieziyu** [comment]
@zzcfree 
已发布 v1.4.0 版本，可以使用这些服务

**Comment by zzcfree** [comment]
发现v1.4.0版本的一个小bug， 驾车路线规划正常，货车路线死活不出来，也不报任何错，查找发现原来此版本默认使用amap的 1.4.3旧版，而货车路线规划是在官方1.4.4以后加入的
