### ISSUE TITLE
marker和  map的 center属性冲突

### ISSUE THREAD

**Issue by zhangrenjian** [xieziyu/ngx-amap#47]
我现在安装最新版本2.2.1， 参考文档demo，显示一个marker点标记，但是只要 设置了center属性，里面有marker，地图就不显示了，例如最简单的demo
<ngx-amap class="demo-map" [resizeEnable]="true" [center]="[116.397428, 39.90923]" [zoom]="13">
  <amap-marker [position]="[116.397428, 39.90923]" [hidden]="hidden" [icon]="icon" [label]="label"></amap-marker>
</ngx-amap>

**Comment by xieziyu** [comment]
@zhangrenjian 
demo示例的代码和这个一样，可以正常显示的，有看到抛出什么错误吗？

**Comment by zhangrenjian** [comment]
感谢回复，是我粗心，把经纬度传反了，，，，




------------------ 原始邮件 ------------------
发件人: "Xie, Ziyu"<notifications@github.com>; 
发送时间: 2019年9月25日(星期三) 中午11:06
收件人: "xieziyu/ngx-amap"<ngx-amap@noreply.github.com>; 
抄送: "说了再见"<509634685@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [xieziyu/ngx-amap] marker和  map的 center属性冲突 (#47)




@zhangrenjian
 demo示例的代码和这个一样，可以正常显示的，有看到抛出什么错误吗？
