### ISSUE TITLE
在线文档的两个错误

### ISSUE THREAD

**Issue by ysfb2000** [xieziyu/ngx-amap#48]
1.amap-text的简单示例中的Html内容使用的是amap-marker标签，应该是amap-text

2.AmapMouseToolService的简单示例和事件的component代码
` ngAfterViewInit() {
    this.plugin = this.mapComponent.ready
      .take(1)
      .toPromise()
      .then((map: Map) => this.mouseToolService.of(map));
  }`

应该改为
` ngAfterViewInit() {
    this.plugin = this.mapComponent.ready
      .pipe(take(1))
      .toPromise()
      .then((map: Map) => this.mouseToolService.of(map));
  }`

**Comment by WilsonLau0755** [comment]
刚也看到这里。
AmapMouseToolService的简单实例处import是不是也要改？我的项目中会报错。
import 'rxjs/add/operator/take';
改成
import { take } from 'rxjs/operators';
再加上上面修改pipe才OK。

**Comment by xieziyu** [comment]
@ysfb2000 @WilsonLau0755 
感谢，是的，因为项目比较久了，示例写的还是 rxjs 6.0 之前的版本，会更新的！

**Comment by ysfb2000** [comment]
是的，谢谢你的开源项目，让我这里的工作轻松了许多





在 2019-10-17 11:25:09，"Wilson Lau" <notifications@github.com> 写道：


刚也看到这里。
AmapMouseToolService的简单实例处import是不是也要改？我的项目中会报错。
import 'rxjs/add/operator/take';
改成
import { take } from 'rxjs/operators';
再加上上面修改pipe才OK。
