### ISSUE TITLE
amap-marker 切换标注图片加载不出来

### ISSUE THREAD

**Issue by boloboloda** [xieziyu/ngx-amap#53]
ngx-amap version: 2.2.1  

` this.icon = this.icon
      ? null
      : {
          size: {
            width: 40,
            height: 50,
          },
          image: 'http://webapi.amap.com/theme/v1.3/images/newpc/way_btn2.png',
          imageOffset: {
            x: 0,
            y: -60,
          },
        };`

demo里的切换可以显示。
[https://lbs.amap.com/api/amap-ui/demos/amap-ui-simplemarker/custom-icon](url)
换成 `http://webapi.amap.com/theme/v1.3/markers/b/mark_r.png`，图片不显示。

**Comment by xieziyu** [comment]
@boloboloda 
mark_r.png不显示是不是因为imageOffset调整的不对？

**Comment by boloboloda** [comment]
mark_r.png imageOffset设置了官方demo的值，还是不显示。
但是鼠标移动上去光标会变应该不是imageOffset的问题。

**Comment by xieziyu** [comment]
@boloboloda 
官方例子设的是基点offset不是imageOffset，你把imageOffset设成0, 0 应该能显示的，还需要调整缩放和大小。我的例子里面imageOffset是因为那张图片包含了个icon，要做裁剪。mark_r.png 不需要裁剪

**Comment by boloboloda** [comment]
@xieziyu 感谢回复。
谢谢你的解答，可以显示了，如你所说，尺寸有点大。
现在的版本支持这种效果吗，[https://lbs.amap.com/api/amap-ui/demos/amap-ui-simplemarker/set-icon-label](url)。

**Comment by xieziyu** [comment]
当前版本暂未支持AMapUI的组件，需要手动加载API使用。后续大版本更新会支持

**Comment by boloboloda** [comment]
@xieziyu 非常感谢！

**Comment by giscafer** [comment]
@boloboloda 1.x版本个人修改已支持AMapUI 组件，如需使用请尝试用 [ngx-amap-yzt](https://www.npmjs.com/package/ngx-amap-yzt)

相关PR #54
