### ISSUE TITLE
angular9 ivy 报错

### ISSUE THREAD

**Issue by wohugb** [xieziyu/ngx-amap#58]
`NullInjectorError: No provider for InjectionToken NGX_AMAP_CONFIG!`

**Comment by xieziyu** [comment]
import NgxAmapModule 的时候有用 .forRoot 吗？

**Comment by wohugb** [comment]
用了 `NgxAmapModule.forRoot({ apiKey: '**', debug: true }),`，不过没在主module里

**Comment by wohugb** [comment]
刚放在 app.module.ts 就可以用了，以前是放在子module里也是可以的

**Comment by yangpu** [comment]
不在app.module里面import，在子模块里面import，lazy loading模式会报错：

`
ERROR Error: Uncaught (in promise): NullInjectorError: R3InjectorError(ReportingModule)[AMapLoaderService -> AMapLoaderService -> InjectionToken NGX_AMAP_CONFIG -> InjectionToken NGX_AMAP_CONFIG -> InjectionToken NGX_AMAP_CONFIG]: 
  NullInjectorError: No provider for InjectionToken NGX_AMAP_CONFIG!
`

**Comment by xieziyu** [comment]
3.0.3版本已修复此问题，可以在子模块 lazy loading 中使用
