### ISSUE TITLE
AmapAutocompleteService导致页面滚动条错误

### ISSUE THREAD

**Issue by 165081945** [xieziyu/ngx-amap#62]
AmapAutocompleteService服务动态生成的div => class="amap-sug-result" ，样式默认没有隐藏。然后绝对定位，跑出body外面去了，所以页面就有产生了一个body的滚动条。而后台框架内容区域的滚动条是在nz-layout内的，所以就看见了2个滚动条。
![截图](https://user-images.githubusercontent.com/62005941/76287163-bceafd00-62de-11ea-9490-a40db8e7ff07.png)

**Comment by xieziyu** [comment]
感谢提醒！已更新示例
